### ISSUE TITLE
verifier fails with AttributeError: 'NoneType' object has no attribute 'checksum'

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1306]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora36-Fedora38, C9S
 * Processor architecture:  x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current latest upstream [fb817ee](https://github.com/keylime/keylime/commit/fb817eef80bbde83e07945d5e0d66141b2ab5679)

# Description 
`keylime_verifier` fails to attest an agent and fails with the following error

```
Feb 10 14:33:00 ip-172-31-30-136.us-east-2.compute.internal keylime_verifier[123613]: 2023-02-10 14:33:00.446 - keylime.verifier - ERROR - Polling thread error for agent ID d432fbb3-d2f1-4a97-9ef7-75bd81c00000: 'NoneType' object has no attribute 'checksum'
keylime_verifier[123613]: 2023-02-10 14:33:00.446 - keylime.verifier - ERROR - 'NoneType' object has no attribute 'checksum'
keylime_verifier[123613]: Traceback (most recent call last):
keylime_verifier[123613]:   File "/usr/local/lib/python3.9/site-packages/keylime-6.6.0-py3.9.egg/keylime/cloud_verifier_tornado.py", line 1310, in process_agent
keylime_verifier[123613]:     runtime_policy = verifier_read_policy_from_cache(stored_agent)
keylime_verifier[123613]:   File "/usr/local/lib/python3.9/site-packages/keylime-6.6.0-py3.9.egg/keylime/cloud_verifier_tornado.py", line 135, in verifier_read_policy_from_cache
keylime_verifier[123613]:     if stored_agent.ima_policy.checksum not in GLOBAL_POLICY_CACHE[str(stored_agent.agent_id)]:
keylime_verifier[123613]: AttributeError: 'NoneType' object has no attribute 'checksum'
```
This is a regression introduced with https://github.com/keylime/keylime/pull/1272.
This bug has not been catched in CI, unfortunately the respective test has been accidentally disabled during the IMA policy overhaul update.

## Expected behavior vs. actual behavior 
verifier works properly and attests an agent

## Steps to reproduce problem
1. see last test results of e2e test /functional/tenant-runtime-policy-sanity

# Relevant logs
Logs from Rawhide are currently available at
https://artifacts.dev.testing-farm.io/2db622b2-5743-4765-b867-6c9094e9b098/work-upstream-keylime-tests-github-ci_zf645l9/plans/upstream-keylime-tests-github-ci/execute/data/functional/tenant-runtime-policy-sanity/data/

**Comment by maugustosilva** [comment]
@mdrocco looks like one of the tests was accidentally disabled

**Comment by maugustosilva** [comment]
The fix seems simple enough, will take a look.

**Comment by mdrocco** [comment]
Thanks, in fact that spot of the code has always been problematic with respect to my type-fixing adventure. Let me know if I can help somehow to fix this.

**Comment by maugustosilva** [comment]
@mdrocco submitted a bugfix
