### PR TITLE
Fix durable attestation in absence of mb_policy

### LINKED ISSUE #1534: keylime_attest fails with a traceback when agent doesn't have mb policy
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current upstream ([a5a671f](https://github.com/keylime/keylime/commit/a5a671f71ce5ed425bc2afa7e81f87fe682936f3))

# Description 
In the latest PR for keylime-tests I have noticed a new test failure. It happens in /regression/CVE-2023-3674 which is not yet enabled in keylime upstream CI plan.

```
:: [ 16:35:54 ] :: [  BEGIN   ] :: Running 'keylime_attest'
INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
2024-03-15 16:35:54.852 - keylime.config - INFO - Reading configuration from ['/etc/keylime/verifier.conf']
2024-03-15 16:35:54.854 - keylime.measured_boot - DEBUG - mba.elchecking.elchecker: policy names = ['accept-all', 'reject-all']
2024-03-15 16:35:54.855 - keylime.keylime.cmd_exec - DEBUG - Executing command "tpm2_startup --version"
2024-03-15 16:35:54.863 - keylime.elparsing - DEBUG - mba.elparser.tpm2_tools_elparser: TPM2-TOOLS 5.4 detected.
2024-03-15 16:35:54.863 - keylime.config - INFO - Reading configuration from ['/etc/keylime/registrar.conf']
2024-03-15 16:35:54.864 - keylime.durable_attestation - INFO - The "Durable Attestion" feature is stil experimental and might change in the future
2024-03-15 16:35:54.864 - keylime.durable_attestation - DEBUG - Persistent store module keylime.da.examples.file imported for "Durable Attestation"
2024-03-15 16:35:54.864 - keylime.durable_attestation_fetch_and_replay - INFO - => Selected date range for attestation records is: start 0 (1970-01-01T00:00:00.000000) and end 99999999999 (5138-11-16T09:46:39.000000)
2024-03-15 16:35:54.864 - keylime.durable_attestation_fetch_and_replay - INFO - => Getting a list of agents registered on the persistent store
2024-03-15 16:35:54.864 - keylime.durable_attestation_persistent_store - DEBUG - Extracting the UUIDs of all agents with entries with prefix CI_registration from filesystem persistent store
2024-03-15 16:35:54.864 - keylime.durable_attestation_fetch_and_replay - INFO - ===> Getting all existing registration records for agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000...
2024-03-15 16:35:54.864 - keylime.durable_attestation_persistent_store - DEBUG - Extracting all records for record_identifier /var/lib/keylime/da/CI_registration_d432fbb3-d2f1-4a97-9ef7-75bd81c00000.json from filesystem persistent store
2024-03-15 16:35:54.864 - keylime.durable_attestation - DEBUG - New AIK added to the list
2024-03-15 16:35:54.864 - keylime.durable_attestation_fetch_and_replay - INFO - ===> Getting all existing attestation records for agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 ...
2024-03-15 16:35:54.864 - keylime.durable_attestation_persistent_store - DEBUG - Extracting all records for record_identifier /var/lib/keylime/da/CI_attestation_d432fbb3-d2f1-4a97-9ef7-75bd81c00000.json from filesystem persistent store
2024-03-15 16:35:54.866 - keylime.durable_attestation_fetch_and_replay - INFO - =====> Verifing the state of agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 over time...
Traceback (most recent call last):
  File "/usr/local/bin/keylime_attest", line 33, in <module>
    sys.exit(load_entry_point('keylime==7.10.0', 'console_scripts', 'keylime_attest')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keylime-7.10.0-py3.11.egg/keylime/cmd/attest.py", line 16, in main
    attest.main()
  File "/usr/local/lib/python3.11/site-packages/keylime-7.10.0-py3.11.egg/keylime/da/attest.py", line 107, in main
    mb_policy = json.loads(attestation_record["mb_policy"])
                           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'mb_policy'
```

The failure was surprising at first because it is doing similar setup as the passing test /functional/durable-attestion-sanity-on-localhost . After closer look it seems that the culprit is that /regression/CVE-2023-3674 does not provide mbpolicy when adding the agent
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/regression/CVE-2023-3674/test.sh#L56

## Expected behavior vs. actual behavior 
`keylime_attest` is failing when mbpolicy is not present. `keylime_attest` should work even when mbpolicy is not present.

## Steps to reproduce problem
1.  See https://github.com/RedHat-SP-Security/keylime-tests/blob/main/regression/CVE-2023-3674/test.sh

# Relevant logs
https://artifacts.dev.testing-farm.io/3f7603e7-3443-4b93-bdb9-30eda37cfd77/

### PR DESCRIPTION
**Pull request by niteeshkd**
Fixes #1534

### CODE REVIEW

**Comment by niteeshkd** [comment]
@kkaarreell

**Comment by kkaarreell** [comment]
The failure on Rawhide is unrelated and will be fixed with https://github.com/RedHat-SP-Security/keylime-tests/pull/561

**Comment by stefanberger** [comment]
The following linter issue should go away once you rebase on latest master.
```
[6912] /__w/keylime/keylime$ /__w/keylime/keylime/.tox/mypy/bin/mypy keylime/
keylime/dsse/dsse.py:66: error: Unused "type: ignore" comment  [unused-ignore]
Found 1 error in 1 file (checked 128 source files)
ERROR: InvocationError for command /__w/keylime/keylime/.tox/mypy/bin/mypy keylime/ (exited with code 1)
```

**Review by THS-on — APPROVED** [review]

**Review by maugustosilva — APPROVED** [review]
